In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("wdifact.csv")
df.head()

,COUNTRYNAME,COUNTRYCODE,INDICATORNAME,INDICATORCODE,YEAR,INDICATORVALUE
0,IBRD only,IBD,"Population, total",SP.POP.TOTL,2000,3.983328e+09
1,IBRD only,IBD,"Population, total",SP.POP.TOTL,2001,4.031081e+09
2,IBRD only,IBD,"Population, total",SP.POP.TOTL,2002,4.077229e+09
3,IBRD only,IBD,"Population, total",SP.POP.TOTL,2003,4.122776e+09
4,IBRD only,IBD,"Population, total",SP.POP.TOTL,2004,4.168677e+09

In [3]:
df.shape

(56513, 6)

In [4]:
countries=[
    'Australia',
    'Brazil',
    'Canada',
    'China',
    'Denmark',
    'Finland',
    'France',
    'Germany',
    'Hong Kong SAR, China',
    'India',
    'Italy',
    'Japan',
    'Korea, Rep.',
    'Luxembourg',
    'Mexico',
    'Netherlands',
    'New Zealand',
    'Norway',
    'Qatar',
    'Russian Federation',
    'Saudi Arabia',
    'Singapore',
    'Spain',
    'Sweden',
    'Switzerland',
    'Turkiye',
    'United Arab Emirates',
    'United Kingdom',
    'United States'
]

In [5]:
df=df[df['COUNTRYNAME'].isin(countries)]
df.head()

,COUNTRYNAME,COUNTRYCODE,INDICATORNAME,INDICATORCODE,YEAR,INDICATORVALUE
7632,Australia,AUS,GDP (current US$),NY.GDP.MKTP.CD,2000,4.161680e+11
7633,Australia,AUS,GDP (current US$),NY.GDP.MKTP.CD,2001,3.796290e+11
7634,Australia,AUS,GDP (current US$),NY.GDP.MKTP.CD,2002,3.957890e+11
7635,Australia,AUS,GDP (current US$),NY.GDP.MKTP.CD,2003,4.677390e+11
7636,Australia,AUS,GDP (current US$),NY.GDP.MKTP.CD,2004,6.146600e+11

In [6]:
df.drop_duplicates(inplace=True)

In [7]:
data=df.pivot(index=['COUNTRYNAME','YEAR'],columns='INDICATORNAME',values='INDICATORVALUE')
data

INDICATORNAME       Agriculture, forestry, and fishing, value added (% of GDP)  \
COUNTRYNAME   YEAR
Australia     2000                                           3.110428
              2001                                           3.496880
              2002                                           3.945027
              2003                                           2.887407
              2004                                           3.061606
...                                                               ...
United States 2020                                           0.762828
              2021                                           0.965413
              2022                                           1.115081
              2023                                           0.989069
              2024                                           0.851091

INDICATORNAME       GDP (current US$)  \
COUNTRYNAME   YEAR
Australia     2000       4.161680e+11
              2001       3.796290e+11
              2002       3.957890e+11
              2003       4.677390e+11
              2004       6.146600e+11
...                               ...
United States 2020       2.135410e+13
              2021       2.368120e+13
              2022       2.600690e+13
              2023       2.772070e+13
              2024       2.918490e+13

INDICATORNAME       Industry (including construction), value added (% of GDP)  \
COUNTRYNAME   YEAR
Australia     2000                                          24.550533
              2001                                          23.633521
              2002                                          23.611732
              2003                                          24.042096
              2004                                          23.934919
...                                                               ...
United States 2020                                          17.115786
              2021                                          17.495381
              2022                                          18.083598
              2023                                          17.745870
              2024                                          17.325644

INDICATORNAME       Inflation, GDP deflator (annual %)  Population, total  \
COUNTRYNAME   YEAR
Australia     2000                            2.550765         19028802.0
              2001                            4.630741         19274701.0
              2002                            2.840354         19495210.0
              2003                            2.985545         19720737.0
              2004                            3.232299         19932722.0
...                                                ...                ...
United States 2020                            1.328833        331577720.0
              2021                            4.565986        332099760.0
              2022                            7.129481        334017321.0
              2023                            3.598391        336806231.0
              2024                            2.418098        340110988.0

INDICATORNAME       Services, value added (% of GDP)  \
COUNTRYNAME   YEAR
Australia     2000                         64.368151
              2001                         64.165354
              2002                         63.953144
              2003                         64.270559
              2004                         64.246507
...                                              ...
United States 2020                         80.011056
              2021                         79.492159
              2022                         78.689054
              2023                         79.138874
              2024                         79.676062

INDICATORNAME       Stocks traded, total value (% of GDP)  \
COUNTRYNAME   YEAR
Australia     2000                              51.234935
              2001                              63.369782
              2002                              73.510437
              2003                              90.150620
              2004                              88.654270
...                                                   ...
United States 2020                             192.405448
              2021                             193.715697
              2022                             170.400560
              2023                             134.423740
              2024                             145.966653

INDICATORNAME       Tax revenue (% of GDP)  Trade (% of GDP)
COUNTRYNAME   YEAR
Australia     2000               23.024142         40.935211
              2001               24.857860         44.218705
              2002               23.548145         41.449092
              2003               24.299970         40.201567
              2004               24.258265         37.009614
...                                    ...               ...
United States 2020               10.153422         23.079778
              2021               11.394678         25.213656
              2022               12.598904         26.891690
              2023               10.645913         24.899363
              2024                     NaN         24.887992

[725 rows x 9 columns]

In [8]:
cols=['Agriculture, forestry, and fishing, value added (% of GDP)',
       'Industry (including construction), value added (% of GDP)',
       'Services, value added (% of GDP)',
       'Stocks traded, total value (% of GDP)', 
       'Tax revenue (% of GDP)',
       'Trade (% of GDP)']

In [9]:
for col in cols:
    data[f'{col}(current US$)']=data[f'{col}']*data['GDP (current US$)']

In [10]:
data['GDP per Capita']=data['GDP (current US$)']/data['Population, total']

In [11]:
data['GDP Growth']=data['GDP (current US$)'].pct_change()*100

C:\Users\ayman\AppData\Local\Temp\ipykernel_10444\4253020782.py:1: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  data['GDP Growth']=data['GDP (current US$)'].pct_change()*100

In [12]:
data=data.reset_index()
data

INDICATORNAME,COUNTRYNAME,YEAR,"Agriculture, forestry, and fishing, value added (% of GDP)",GDP (current US$),"Industry (including construction), value added (% of GDP)","Inflation, GDP deflator (annual %)","Population, total","Services, value added (% of GDP)","Stocks traded, total value (% of GDP)",Tax revenue (% of GDP),Trade (% of GDP),"Agriculture, forestry, and fishing, value added (% of GDP)(current US$)","Industry (including construction), value added (% of GDP)(current US$)","Services, value added (% of GDP)(current US$)","Stocks traded, total value (% of GDP)(current US$)",Tax revenue (% of GDP)(current US$),Trade (% of GDP)(current US$),GDP per Capita,GDP Growth
0,Australia,2000,3.110428,4.161680e+11,24.550533,2.550765,19028802.0,64.368151,51.234935,23.024142,40.935211,1.294461e+12,1.021715e+13,2.678796e+13,2.132234e+13,9.581911e+12,1.703592e+13,21870.425684,NaN
1,Australia,2001,3.496880,3.796290e+11,23.633521,4.630741,19274701.0,64.165354,63.369782,24.857860,44.218705,1.327517e+12,8.971970e+12,2.435903e+13,2.405701e+13,9.436765e+12,1.678670e+13,19695.714087,-8.779868
2,Australia,2002,3.945027,3.957890e+11,23.611732,2.840354,19495210.0,63.953144,73.510437,23.548145,41.449092,1.561398e+12,9.345264e+12,2.531195e+13,2.909462e+13,9.320097e+12,1.640509e+13,20301.858764,4.256788
3,Australia,2003,2.887407,4.677390e+11,24.042096,2.985545,19720737.0,64.270559,90.150620,24.299970,40.201567,1.350553e+12,1.124543e+13,3.006185e+13,4.216696e+13,1.136604e+13,1.880384e+13,23718.129804,18.178878
4,Australia,2004,3.061606,6.146600e+11,23.934919,3.232299,19932722.0,64.246507,88.654270,24.258265,37.009614,1.881847e+12,1.471184e+13,3.948976e+13,5.449223e+13,1.491059e+13,2.274833e+13,30836.731682,31.410894
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
720,United States,2020,0.762828,2.135410e+13,17.115786,1.328833,331577720.0,80.011056,192.405448,10.153422,23.079778,1.628950e+13,3.654922e+14,1.708564e+15,4.108645e+15,2.168172e+14,4.928479e+14,64401.492356,-0.863045
721,United States,2021,0.965413,2.368120e+13,17.495381,4.565986,332099760.0,79.492159,193.715697,11.394678,25.213656,2.286213e+13,4.143116e+14,1.882470e+15,4.587420e+15,2.698397e+14,5.970896e+14,71307.489051,10.897673
722,United States,2022,1.115081,2.600690e+13,18.083598,7.129481,334017321.0,78.689054,170.400560,12.598904,26.891690,2.899981e+13,4.702983e+14,2.046458e+15,4.431590e+15,3.276584e+14,6.993695e+14,77860.932248,9.820871
723,United States,2023,0.989069,2.772070e+13,17.745870,3.598391,336806231.0,79.138874,134.423740,10.645913,24.899363,2.741769e+13,4.919279e+14,2.193785e+15,3.726320e+15,2.951122e+14,6.902278e+14,82304.593706,6.589790
724,United States,2024,0.851091,2.918490e+13,17.325644,2.418098,340110988.0,79.676062,145.966653,NaN,24.887992,2.483901e+13,5.056472e+14,2.325338e+15,4.260022e+15,NaN,7.263535e+14,85809.929787,5.281973

In [13]:
#df=data.melt(id_vars=['COUNTRYNAME','YEAR'],value_vars=list(data.columns),var_name='IndicatorName',value_name='IndicatorValue')

In [14]:
data.to_csv("Facts.csv")